name: Build
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for better analysis
 
      - name: Cache SonarScanner CLI
        id: cache-sonar
        uses: actions/cache@v4
        with:
          path: /home/runner/work/_temp/sonar-scanner-7.0.2.4839-linux-x64
          key: sonar-scanner-cli-7.0.2.4839-linux-x64
 
      - name: Set up SonarQube scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.0.2.4839-linux-x64.zip -O sonar-scanner.zip
          unzip sonar-scanner.zip -d /home/runner/work/_temp/
          ls /home/runner/work/_temp/sonar-scanner-7.0.2.4839-linux-x64/bin
 
      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://e5a6-125-19-120-130.ngrok-free.app"
        run: |
          /home/runner/work/_temp/sonar-scanner-7.0.2.4839-linux-x64/bin/sonar-scanner \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.login=${SONAR_TOKEN}
